learning_user_auth/basic_userapp/urls.py
from django.urls import path

from basic_userapp import views

from django.conf import settings

from django.conf.urls.static import static

#TEMPLATE URLS!
app_name = 'basic_userapp'

urlpatterns = [

    path('register/',views.register,name='register'),
    path('user_login/',views.user_login,name='user_login'),
]


#urlpatterns = [  ... the rest of your URLconf goes here ... ]

learning_user_auth/learning_user_auth/urls.py
from django.contrib import admin
from django.urls import path,include
from basic_userapp import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.index,name='index'),
    path('basic_userapp/',include('basic_userapp.urls')),
    path('logout/',views.user_logout,name='logout'),
    #path('appreciate/',views.appreciate,name='appreciate')
]

learning_user_auth/basic_userapp/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class UserProfileInfo(models.Model):

    user = models.OneToOneField(User,on_delete=models.CASCADE)

    portfolio_site = models.URLField(blank=True)

    profile_pic = models.ImageField(upload_to='profile_pics', blank=True)

    def __str__(self):
        return self.user.username #username is default attribute of User

#NEXT LECTURE GOING TO LEARN HOW TO CONNET ALL OF THESE TOGETHER

learning_user_auth/basic_userapp/forms.py
from django import forms
from django.contrib.auth.models import User
from basic_userapp.models import UserProfileInfo

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model = User
        fields = ('username', 'email', 'password')

class UserInformationForm(forms.ModelForm):
    class Meta():
        model = UserProfileInfo
        fields = ('portfolio_site', 'profile_pic')

learning_user_auth/basic_userapp/views.py
from django.shortcuts import render
from basic_userapp.forms import UserForm,UserInformationForm

from django.contrib.auth import authenticate,login,logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required


# Create your views here.
# A LOT OF CODING FOR WORKING WITH USERS AND AUTHORIZATION HAPPENS IN THE VIEWS.PY FILE
#BASIC IDEA IS THAT WE CHECK IF THERRE IS A POST REQUEST AND THEN PERFORM SOME SORT OF ACTION BASED OFF THAT INFORMATION
#FIGURING OUT TH ERGISTRATION VIEWS IS AN EXTENTION OF WHAT WE LEARN ABOUT WHEN DISCUSSING DJANGO FORMS MAKE SURE TO REWIEW THAT CONTENT IF  NOT REMEMBERING

def index(request):
    return render(request,'basic_userapp/index.html')

@login_required
def appreciate(request):
    return HttpResponse("THANKYOU FOR LOGGING IN,YOU'RE AWESOME!")


@login_required
def user_logout(request):
    logout(request)#REVISE THIS PART
    return HttpResponseRedirect(reverse('index'))


def register(request):

    registered = False

    if request.method == "POST":
        user_form = UserForm(data=request.POST)
        profile_form = UserInformationForm(data=request.POST)
        if user_form.is_valid() and profile_form.is_valid():

            user = user_form.save()
            user.set_password(user.password)#this is setting the password as the hash
            user.save()

            profile = profile_form.save(commit=False)# SETTING UP THE ONE2ONE RELATIONSHIP DEFINED IN MODELS.PY
            profile.user = user

            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']

            profile.save()

            registered = True
        else:
            print(user_form.errors,profile_form.errors)
    else:
        user_form = UserForm()
        profile_form = UserInformationForm()
    return render(request, 'basic_userapp/registration.html',
                            {'user_form':user_form,
                            'profile_form':profile_form,
                            'registered':registered,})


def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username,password=password)

        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('index'))

            else:
                return HttpResponse("ACCOUNT NOT ACTIVE")


        else:
            print("SOmeone Tried to Login And Failed")
            print("Username: {} and password {}".format(username,password))
            return HttpResponse("invalid login details supplied!")

    else:
        return render(request,'basic_userapp/login.html',{})

learning_user_auth/templates/basic_userapp/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" crossorigin="anonymous">
  </head>
  <body>
    <nav class="navbar navbar-dark bg-dark">
      <div class="container">
        <ul class="nav navbar-nav">
          <li><a class = "navbar-brand" href="{% url 'index' %}">DJANGO HOME</a></li>
          <li class="nav-item nav-link active"><a class="nav-link" href="{% url 'admin:index' %}">ADMIN</a></li>
          <li class="nav-item nav-link active"><a class="nav-link" href="{% url 'basic_userapp:register' %}">REGISTER</a></li>


          {% if user.is_authenticated %}
            <li class="nav-item nav-link active"><a class="nav-link" href="{% url 'logout' %}">LOGOUT</a></li>
          {% else %}
            <li class="nav-item nav-link active"><a class="nav-link" href="{% url 'basic_userapp:user_login' %}">LOGIN</a></li>
          {% endif %}



        </ul>
      </div>
    </nav>
    <div class="container">
      {% block body_block %}
      {% endblock%}
    </div>

  </body>
</html>
<!-- this page has navbar with links and urls  -->

learning_user_auth/templates/basic_userapp/index.html
{% extends "basic_userapp/base.html"%}
{% block body_block %}

<div class="jumbotron">
  <h1>WELCOME TO DEEPANKAR'S WEBSITE</h1>
</div>

{% endblock %}
<!-- #nothing much on this page  -->

learning_user_auth/templates/basic_userapp/login.html
<!DOCTYPE html>
{% extends 'basic_userapp/base.html'%}
{% block body_block %}

<div class="jumbotron">

  <h1>Please Login</h1>
  <form class="" action="{% url 'basic_userapp:user_login' %}" method="post">
    {% csrf_token %}
    <label for="username">Username:</label>
    <input type="text" name="username" placeholder="Enter Username"><br>

    <label for="password">Password:</label>
    <input type="password" name="password" placeholder="Enter Password"><br>

    <input type="submit" name="" value="Login"><br>
  </form>


</div>







{% endblock %}

learning_user_auth/templates/basic_userapp/registration.html
{% extends "basic_userapp/base.html"%}
{% load static %}

{% block body_block %}


<div class="jumbotron">
  {% if registered %}
    <h1>Thankyou For registering </h1>
  {% else %}
    <h1>Register Here!</h1>
    <h3>Fill out The Form></h3>
    <form  method="POST" enctype="multipart/form-data">#enctype is to facilitate image uploading
      {% csrf_token %}
      {{ user_form.as_p }}
      {{ profile_form.as_p }}
      <input type="submit" name="" value="Register">
    </form>
    {% endif %}
</div>
 {% endblock %}
<!-- #this page has the tokens user forms and profile forms from forms.py -->